version: '3'

services:
  # FastAPI service
  authentication:
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    # for hot-reloading
    volumes:
      - ./authentication:/app
